#!/usr/bin/env bash
# PART 2 - 50 real per-project issues (2 per project 01-25). SINGLE run, parallel xargs -P 8.
set -uo pipefail
REPO="jaikaran109/51_Web_Projects"
P="https://github.com/jaikaran109/51_Web_Projects/tree/main"
B="https://github.com/jaikaran109/51_Web_Projects/blob/main"
for l in "hacktoberfest|FF7518" "level 1|0E8A16" "level 2|FBCA04" "level 3|D93F0B" "security|000000" "accessibility|5319E7"; do n="${l%%|*}"; c="${l##*|}"; gh label create "$n" --repo "$REPO" --color "$c" >/dev/null 2>&1 || true; done
F=$(mktemp); trap 'rm -f "$F"' EXIT
Q() { printf '%s\t%s\t%s\n' "$1" "$2" "$3" >> "$F"; }
Q "[01-Rock-Paper-Scissors]: choices row overflows on 360px, fixed 150px circles" "bug,good first issue" "Project $P/01-Rock-Paper-Scissors -- styles script.css: .choices gap 3rem + .choice 150px + img 130px = ~570px row, scrolls on phones. score-board gap 5rem + msg 2rem overflow. index.html imgs have no alt. Fix: <600px media 92px circles, gap 1rem, msg 1.1rem, add alt, scope text-align. Files: script.css index.html."
Q "[01-Rock-Paper-Scissors]: score resets on reload, no reset button, mouse-only" "enhancement,good first issue" "Project $P/01-Rock-Paper-Scissors -- logic $B/01-Rock-Paper-Scissors/app.js: userScore/compScore in-memory only; no Reset button; div.choice not keyboard accessible (no R/P/S keys, no focus ring). Fix: localStorage persist + Reset btn + button semantics + aria-live msg."

Q "[02-Tic-Tac-Toe]: winning line not highlighted, msg overlay 100vmin, implicit global" "bug,good first issue" "Project $P/02-Tic-Tac-Toe -- logic $B/02-Tic-Tac-Toe/app.js: checkWinner never marks which 3 cells won; for(pattern of ...) missing let = global leak; returns undefined not false; .msg-container height 100vmin layout push. Fix: .win class on 3 cells, let+return false, fixed overlay."
Q "[02-Tic-Tac-Toe]: no scoreboard, no turn indicator, Hinglish comments" "enhancement,good first issue" "Project $P/02-Tic-Tac-Toe -- verified: resetGame clears board but no X/O/Draw tally; no turn indicator; comments in Hinglish + typo winnig. Fix: scoreboard localStorage + turn label + translate comments."
Q "[03-CodeForces-Clone]: 12 nav links dead, search + Find button do nothing" "bug" "Project $P/03-CodeForces-Clone -- page index.html: all 12 header links href empty; search input no label/placeholder; find-btn zero JS; heavy inline styles. Fix: client-side contest filter + mock user lookup + move styles to classes. New app.js."
Q "[03-CodeForces-Clone]: tables overflow mobile, flags no alt, logo squish" "enhancement,good first issue" "Project $P/03-CodeForces-Clone -- styles style.css: tables 100pct no overflow-x wrapper; flag imgs empty alt; logo 50pct distorts; body 95pct+margin-left 25px overflows; Neta 350px fixed. Fix: table-scroll wrapper, alts, fluid imgs."
Q "[04-Job-Application]: form submits empty, CV label mismatch, textarea invalid attr" "bug,good first issue" "Project $P/04-Job-Application -- form index.html: zero required attrs; label for=cv vs input id=upload with duplicate type attr; select no id; textarea type attr invalid + row not rows; Second Name typo. Fix: required+patterns, fix fors, add app.js errors + success card."
Q "[04-Job-Application]: red focus outline + grey hover fail" "enhancement,good first issue" "Project $P/04-Job-Application -- style.css: input focus red-only; button hover grey looks disabled; no bottom margin. Fix: 2px blue focus, darken hover, mobile padding."
Q "[05-Pokemon-Card-Game]: named Game but zero JS, 4 static cards" "bug,good first issue" "Project $P/05-Pokemon-Card-Game -- index.html: no script file; 4 hardcoded .shape divs; title Cards Project vs H1 Gallery mismatch. Fix: app.js memory-match 8 cards shuffle flip moves+timer Play Again, or rename folder."
Q "[05-Pokemon-Card-Game]: hotlinked sprites no fallback, fixed 200px cards" "enhancement,good first issue" "Project $P/05-Pokemon-Card-Game -- 4 imgs hotlink raw.githubusercontent (offline broken), no w/h attrs; .shape 200px fixed overflows. Fix: local images + onerror fallback + auto-fit grid."
Q "[06-Shapes-Games]: no JS, diamond breaks layout, Readme casing wrong" "bug,good first issue" "Project $P/06-Shapes-Games -- index.html: no script tag (hover-only); diamond translate 30px + circle outside box mis-centers; file Readme.md not README.md. Fix: app.js click-target rounds + 30s timer + best; fix nesting; rename readme."
Q "[06-Shapes-Games]: 200px fixed shapes, aqua heading, no wrap" "enhancement,good first issue" "Project $P/06-Shapes-Games -- style.css: 3x200px row no wrap scrolls phones; heading aqua harsh; global h1 weight normal. Fix: flex-wrap + min(40vw,200px) + scope h1."
Q "[07-Tribute-Website]: CSS link 404 + image 404, page totally broken" "bug,good first issue" "Project $P/07-Tribute-Website -- index.html links Tribute_Style.css but disk file is style.css (zero styles load); img ./image/apj.png but disk file is A._P._J._Abdul_Kalam.jpg.webp (404); selector .image_container,img hits every img. Fix link+src+scope + screenshot proof."
Q "[07-Tribute-Website]: biography list pasted twice + no mobile CSS" "bug,good first issue" "Project $P/07-Tribute-Website L36-102 -- same 8 books twice + garbled Etern-ul nesting; h2 70px no query; css footer rules but html has no footer. Fix: dedupe, clamp h2, stack <768px, add footer."
Q "[08-Amazon-Clone]: title Document, empty alts, all links dead" "bug,good first issue" "Project $P/08-Amazon-Clone -- index.html: title says Document; logo hero box imgs empty alt; panel+footer links href empty. Fix: real title+meta+alts, Back-to-Top scrolls to top."
Q "[08-Amazon-Clone]: navbar and search cramp at tablet widths" "enhancement,good first issue" "Project $P/08-Amazon-Clone -- style.css: navbar fixed 60px not sticky; select 60px; queries only 900/600 so 601-899px cramps. Fix: sticky nav, search min-width, hero cover, footer wrap."
Q "[09-Digital-Clock]: entry is digitalclock.html not index.html, favicon 404" "bug,good first issue" "Project $P/09-Digital-Clock -- entry digitalclock.html breaks convention; icon ../favv.png 404; back link href=/ breaks Pages subpath. Fix: add index.html entry, inline SVG favicon, relative back link."
Q "[09-Digital-Clock]: 7 font families + alarm.mp3 bloat load" "enhancement" "Project $P/09-Digital-Clock -- fonts link loads 7 families; alarm.mp3 binary in repo; 1400-line css. Fix: keep 2 fonts display=swap, lazy below-fold, document mp3 license."
Q "[10-E-Commerce]: no .env.example, hardcoded 5050, seed commented out" "bug" "Project $P/10-E-Commerce_Shopping_App -- server.js: dotenv but no .env.example; PORT 5050 fixed; seedDB commented no npm script. Fix: .env.example + PORT fallback + seed script + README run table."
Q "[10-E-Commerce]: README missing routes + screenshots" "documentation,good first issue" "Project $P/10-E-Commerce_Shopping_App -- verify README lists product/review/auth routes + folder map + test logins + home/cart shots. Fix accordingly."
Q "[11-Square-Game]: sq4 click sets invalid rgb (missing paren)" "bug,good first issue" "Project $P/11-Square-Game -- script.js L63: rgb(3 args missing closing paren = invalid, silently ignored; 2 mouseleave on s1. Fix: close parens, merge handlers, add touchstart + score."
Q "[11-Square-Game]: mouse-only, no touch, no instructions" "enhancement,good first issue" "Project $P/11-Square-Game -- mouseenter/click only, mobile dead; no How-to-play (dblclick box1, click box4). Fix: touch events + help bar + responsive squares."
Q "[12-Pokemon-Collection]: pinimg hotlinks + unquoted src + no alt" "bug,good first issue" "Project $P/12-Pokemon-Card-Collection -- script.js: 7 pinimg hotlinks (block risk); template src unquoted; no alt; 55 random dupes. Fix: local imgs or PokeAPI fetch, quoted src+alt, unique shuffle."
Q "[12-Pokemon-Collection]: empty shell page + tiny 100px cards" "enhancement,good first issue" "Project $P/12-Pokemon-Card-Collection -- index.html just div#main+script; .cards 100px fixed. Fix: header + search filter + responsive size."
Q "[13-Portfolio]: nav + Hire me dead, itachi.png empty alt" "bug,good first issue" "Project $P/13-Portfolio -- index.html: 6 nav href=#, Hire me href=#, img alt empty, typing span empty pre-CSS. Fix: anchor sections, wire Hire me to contact, real alt."
Q "[13-Portfolio]: typing keyframes stop at 80pct, img hover sets font-size" "bug,good first issue" "Project $P/13-Portfolio -- style.css: words 0-80pct only (blank 20pct); img hover font-size no-op; box-shadow solid invalid. Fix: full keyframes, scale hover, valid shadow."
Q "[14-BMI-Calculator]: ft-in parser NaN crash, weight 0 accepted" "bug,good first issue" "Project $P/14-BMI-Calculator -- app.js: split on quote fails 5ft6in; feet/inches NaN unchecked; weight 0 passes. Fix: regex parse + reject <=0/NaN inline + show value + color."
Q "[14-BMI-Calculator]: height type=text, low-contrast inputs, 500px clip" "enhancement,good first issue" "Project $P/14-BMI-Calculator -- height text (no keypad); blue bg light text low contrast; container 500px fixed clips errors. Fix: inputmode decimal, contrast, min-height."
Q "[15-Calculator]: eval() injection + 1++2 and 3..5 accepted" "bug,security" "Project $P/15-Calculator -- script.js L34 eval(expression); unchecked append allows 1++2/3..5; display disabled hurts a11y. Fix: safe parser, block consecutive ops/double dots, readonly+aria-live."
Q "[15-Calculator]: no backspace/keyboard, Infinity on divide-by-zero" "enhancement,good first issue" "Project $P/15-Calculator -- only AC and =; equal gives Infinity on /0. Fix: backspace + keyboard 0-9 Enter Esc + friendly error."
Q "[16-Currency]: EXPOSED API key in app.js + Coverter folder typo" "bug,security" "Project $P/16-Currency- Coverter -- app.js L21 hardcodes exchangerate key IN PUBLIC REPO + folder Coverter with space. URGENT: revoke key, switch keyless open.er-api.com, rename 16-Currency-Converter."
Q "[16-Currency]: no fetch catch, yellow-cyan clash, off-center box" "enhancement,good first issue" "Project $P/16-Currency- Coverter -- fetch no catch (offline stale); yellow+darkcyan harsh; comment admits box not centered. Fix: catch + error + cache fallback, soften palette."
Q "[17-Portfolio-ll]: Download CV empty, typed.js blank when offline" "bug,good first issue" "Project $P/17-Portfolio-ll -- index.html: CV href empty; span.multiple-text empty until CDN loads; nav href=# all. Fix: real resume.pdf + fallback text + anchors."
Q "[17-Portfolio-ll]: no mobile menu, image -30px clip" "enhancement,good first issue" "Project $P/17-Portfolio-ll -- style.css: navbar no hamburger (crush 360px); img margin-left -30px clips; 100vh+fixed header overlap. Fix: hamburger, remove offset, scroll-margin."
Q "[18-Cards-React]: missing key prop, hotlinked logos, wrong package name" "bug,good first issue" "Project $P/18-Cards-Project-Using-ComponentsAndProps -- App.jsx: map no key warning; 6 imgs pinimg/bing hotlink; package name 04-cards-project. Fix: key, local logos, rename."
Q "[18-Cards-React]: static list, no search/filter/sort" "enhancement" "Project $P/18-Cards-Project-Using-ComponentsAndProps -- 6 hardcoded jobs no state. Fix: search role/company + type filter + salary sort."
Q "[19-Gallery-React]: useEffect on pics = infinite fetch loop" "bug" "Project $P/19-Gallery-Project -- App.jsx: useEffect deps [pics,page] but setPics retriggers = fetch storm to picsum. Fix: deps [page] only + abort + loading/error."
Q "[19-Gallery-React]: pagination flashes, no lightbox or lazy alt" "enhancement" "Project $P/19-Gallery-Project -- Pagination takes setPics (clears flash); check Card alt/loading. Fix: keep stale until load + skeleton + lightbox."
Q "[20-Insta-App]: open CORS allow-all + hardcoded 5050 + no env" "bug,security" "Project $P/20-Insta-App -- Backend/server.js: cors() allow-all; PORT 5050 fixed; no dotenv; no health. Fix: env allowlist + PORT fallback + GET /health + .env.example."
Q "[20-Insta-App]: Backend/Frontend have no README, ports unknown" "documentation,good first issue" "Project $P/20-Insta-App -- split folders no root README. Fix: ports + dual install + VITE_API_URL + CORS note."
Q "[21-Notes-Api]: CORS localhost-only breaks prod + port clash" "bug" "Project $P/21-Notes-Api_MongoDB -- Backend/server.js: origin localhost:5173 only; PORT 5050 same as 20/23/24 clash. Fix: ALLOWED_ORIGINS env, unique ports doc, /health."
Q "[21-Notes-Api]: no auth, anyone reads all notes" "enhancement,security" "Project $P/21-Notes-Api_MongoDB -- check noteRoutes/models: likely no user/JWT. Fix: JWT register/login, owner scope, 401 tests + Postman."
Q "[22-Notes-App]: delete button removes WRONG note (idx shadow)" "bug,good first issue" "Project $P/22-Notes-App -- App.jsx: onClick={(idx)=>{deleteNote();}} shadows idx with event, calls no-arg so splice(undefined,1) kills last note. Fix: onClick={()=>deleteNote(idx)}."
Q "[22-Notes-App]: notes vanish reload, no edit, console spam" "enhancement" "Project $P/22-Notes-App -- useState no persist; no edit; X magic margins break mobile; console.logs. Fix: localStorage + edit + confirm + cleanup."
Q "[23-Spotify]: music+album mounted on /api/auth (route collision)" "bug" "Project $P/23-Spotify-Project -- server.js L17-18 mounts music+album on /api/auth same as auth. Fix: /api/music + /api/albums + update callers + route table README."
Q "[23-Spotify]: no README/seed/demo, cannot run" "documentation" "Project $P/23-Spotify-Project -- no README/seed, PORT 5050 clash. Fix: arch+env+run README, 10 royalty-free seed tracks, port doc."
Q "[24-Student-System]: seed require with SPACE path crashes Linux" "bug" "Project $P/24-Student Management System -- server.js: require(../Student Management System/seed) wrong level + space path; folder space breaks scripts. Fix: require ./seed + rename 24-Student-Management-System."
Q "[24-Student-System]: no validation/search/pagination, dup rolls" "enhancement" "Project $P/24-Student Management System -- routes/Student+models: likely no unique roll/search. Fix: validator + unique + ?q + 10/page + delete confirm."
Q "[25-UI-Tailwind]: still default Vite starter, zero sections" "enhancement,good first issue" "Project $P/25-UI-Project-Using-Tailwind -- if App.jsx default hero, build Hero/Features/Pricing/FAQ/Footer + mobile menu + dark toggle."
Q "[25-UI-Tailwind]: verify tailwind v4 wiring + build passes" "bug,good first issue" "Project $P/25-UI-Project-Using-Tailwind -- check vite plugin + css import; npm run build clean; document deploy."
# ---- AT-ONCE parallel push: single xargs call, 8 concurrent (not one-by-one) ----
export REPO
do_one() { line="$1"; t="${line%%$'\t'*}"; rest="${line#*$'\t'}"; l="${rest%%$'\t'*}"; b="${rest#*$'\t'}"; gh issue create --repo "$REPO" --title "$t" --label "$l" --body "$b" 2>&1 | tail -n 1; }
export -f do_one
export SHELL=/bin/bash
xargs -a "$F" -d '\n' -P 8 -I{} bash -c 'do_one "$@"' _ {}
echo "OPEN NOW: $(gh issue list --repo "$REPO" --state open --limit 200 --json number --jq length)"